[build-system]
requires = ["setuptools>=62.3.0"]
build-backend = "setuptools.build_meta"

[project]
name = "mani_skill"
version = "3.0.0b7"
description = "ManiSkill3: A Unified Benchmark for Generalizable Manipulation Skills"
readme = "ManiSkill is a powerful unified framework for robot simulation and training powered by [SAPIEN](https://sapien.ucsd.edu/). The entire stack is as open-source as possible and ManiSkill v3 is in beta release now. Among its features include:\n- GPU parallelized visual data collection system. On the high end you can collect RGBD + Segmentation data at 20k FPS with a 4090 GPU, 10-100x faster compared to most other simulators.\n- Example tasks covering a wide range of different robot embodiments (quadruped, mobile manipulators, single-arm robots) as well as a wide range of different tasks (table-top, locomotion, dextrous manipulation)\n- GPU parallelized tasks, enabling incredibly fast synthetic data collection in simulation\n- GPU parallelized tasks support simulating diverse scenes where every parallel environment has a completely different scene/set of objects\n- Flexible task building API that abstracts away much of the complex GPU memory management code\n\nPlease refer our [documentation](https://maniskill.readthedocs.io/en/latest) to learn more information."
requires-python = ">=3.9"
authors = ["ManiSkill contributors"]
optional-dependencies = { "dev" = ["pytest", "black", "isort", "pre-commit", "build", "twine", "stable_baselines3", "pytest"], "docs" = ["sphinx==6.2.1", "sphinx-autobuild", "pydata_sphinx_theme", "sphinxcontrib.spelling", "sphinx-autodoc-typehints", "sphinx_copybutton", "myst-parser", "sphinx-subfigure", "sphinxcontrib-video", "sphinx-togglebutton", "sphinx_design"] }
dependencies = [
    "pytest>=6.0.0",
]

[tool.pytest.ini_options]
markers = [
    "slow: marks tests as slow (deselect with '-m \"not slow\"')",
    "serial",
    "gpu_sim: marks tests as using the GPU simulation (deselect with '-m \"not gpu_sim\"')",
    "serial",
]
